#!/usr/bin/env bash
# Runs automatically after `azd provision` (part of `azd up`). Azure
# resources already exist at this point (main.bicep/resources.bicep) — this
# hook does the part Bicep can't: the Entra ID app registration (a
# Microsoft Graph object, not an ARM resource), wiring its tenant/client ID
# into the Function App's App Settings, and generating this deployment's
# deployments/<env>/ record.
#
# azd injects its environment's outputs (FUNCTION_APP_NAME,
# RESOURCE_GROUP_NAME, PROXY_BASE_URL, AZURE_ENV_NAME, ...) as env vars.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="${REPO_ROOT}/deployments/${AZURE_ENV_NAME}"
mkdir -p "${DEPLOY_DIR}"

# Scoped to this azd environment's name, not just "OneNote ChatGPT Action" —
# a generic display name would match (and silently reuse) an unrelated
# deployment's app registration if one happens to share that name in the
# same tenant, which is not what "idempotent re-run of THIS deployment"
# should mean.
APP_DISPLAY_NAME="${ENTRA_APP_DISPLAY_NAME:-OneNote ChatGPT Action (${AZURE_ENV_NAME})}"
SIGN_IN_AUDIENCE="${ENTRA_SIGN_IN_AUDIENCE:-AzureADMyOrg}"

TENANT_ID="$(az account show --query tenantId -o tsv)"
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

echo "== postprovision: ${AZURE_ENV_NAME} (tenant ${TENANT_ID}) =="

EXISTING_APP_ID="$(az ad app list --display-name "${APP_DISPLAY_NAME}" --query "[0].appId" -o tsv 2>/dev/null || true)"
if [ -n "${EXISTING_APP_ID}" ]; then
  echo "-- Reusing existing Entra app registration '${APP_DISPLAY_NAME}' (${EXISTING_APP_ID}) --"
  CLIENT_ID="${EXISTING_APP_ID}"
  CLIENT_SECRET="(unchanged — reusing existing app registration, not resetting its secret)"
else
  echo "-- Creating Entra ID app registration (${APP_DISPLAY_NAME}, ${SIGN_IN_AUDIENCE}) --"
  APP_JSON="$(az ad app create --display-name "${APP_DISPLAY_NAME}" --sign-in-audience "${SIGN_IN_AUDIENCE}")"
  CLIENT_ID="$(echo "${APP_JSON}" | node -e "process.stdin.on('data',d=>process.stdout.write(JSON.parse(d).appId))")"

  az ad app permission add --id "${CLIENT_ID}" \
    --api 00000003-0000-0000-c000-000000000000 \
    --api-permissions \
      615e26af-c38a-4150-ae3e-c3b0d4cb1d6a=Scope \
      7427e0e9-2fba-42fe-b0c0-848c9e6a8182=Scope -o none

  SECRET_JSON="$(az ad app credential reset --id "${CLIENT_ID}" --append --display-name "chatgpt-action" --years 2)"
  CLIENT_SECRET="$(echo "${SECRET_JSON}" | node -e "process.stdin.on('data',d=>process.stdout.write(JSON.parse(d).password))")"
fi

echo "-- Wiring ENTRA_TENANT_ID / ENTRA_CLIENT_ID into ${FUNCTION_APP_NAME} --"
az functionapp config appsettings set --name "${FUNCTION_APP_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" \
  --settings \
    ENTRA_TENANT_ID="${TENANT_ID}" \
    ENTRA_CLIENT_ID="${CLIENT_ID}" \
  -o none

echo "-- Writing deployments/${AZURE_ENV_NAME}/config.json --"
cat > "${DEPLOY_DIR}/config.json" <<JSON
{
  "description": "Generated by infra/hooks/postprovision.sh (azd) on $(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "azureSubscriptionId": "${SUBSCRIPTION_ID}",
  "resourceGroup": "${RESOURCE_GROUP_NAME}",
  "location": "${AZURE_LOCATION}",
  "storageAccount": "${AZURE_STORAGE_ACCOUNT_NAME}",
  "functionAppName": "${FUNCTION_APP_NAME}",
  "proxyBaseUrl": "${PROXY_BASE_URL}",
  "entraTenantId": "${TENANT_ID}",
  "entraAppDisplayName": "${APP_DISPLAY_NAME}",
  "entraClientId": "${CLIENT_ID}",
  "signInAudience": "${SIGN_IN_AUDIENCE}",
  "nodeVersion": "22",
  "redirectUris": [],
  "note": "entraClientId and redirectUris are public identifiers, safe to keep here. The client secret is NOT stored here — see this hook's one-time console output, or rotate it with az ad app credential reset."
}
JSON

node "${REPO_ROOT}/scripts/render-openapi.js" "${DEPLOY_DIR}/config.json"

echo ""
echo "== postprovision done =="
echo "Function App:      ${PROXY_BASE_URL}"
echo "Entra tenant:      ${TENANT_ID}"
echo "Entra Client ID:   ${CLIENT_ID}"
echo "Entra Client Secret: ${CLIENT_SECRET}"
echo "OpenAPI spec:      ${DEPLOY_DIR}/openapi.yaml"
echo ""
echo "Next: run 'azd deploy' (or just 'azd up' again) to publish the code,"
echo "then import the OpenAPI spec into the GPT Builder and register the"
echo "callback URL ChatGPT shows you:"
echo "  az ad app update --id ${CLIENT_ID} --web-redirect-uris \"<callback URL>\""
